package app;

import java.awt.Color;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.KeyEvent;
import java.awt.event.MouseListener;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Set;
import java.util.Vector;

import javax.swing.AbstractAction;
import javax.swing.DefaultCellEditor;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.KeyStroke;
import javax.swing.plaf.basic.BasicComboBoxUI;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumn;

import ca.odell.glazedlists.GlazedLists;
import ca.odell.glazedlists.swing.AutoCompleteSupport;

import com.fasterxml.jackson.databind.ObjectMapper;

import java.awt.event.KeyAdapter;

import javax.swing.JLabel;
import javax.swing.GroupLayout.Alignment;
import javax.swing.GroupLayout;
import javax.swing.LayoutStyle.ComponentPlacement;

import org.apache.poi.ss.usermodel.Cell;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Abby
 */
public class DCAddBookToPOScreen extends javax.swing.JFrame {
	
	String prevPage;
	private static String purchaseOrderNumber;
	private static String contactPerson;
	private static String outlet;
	private static String dateToday;
	private static List<String> booksList = new ArrayList<String>();
	private static List<String> quantityList = new ArrayList<String>();
	private String []co;
	private List<String> bookAutoList  = new ArrayList<String>();
	private  JComboBox comboBox = new JComboBox();
	private String title;
	private String stocksOnHand;
	
    /**
     * Creates new form DCAddBookToPOScreen
     */
    public DCAddBookToPOScreen(String purchaseOrderNumber1, String dateToday1, String contactPerson1, String outlet1, List<String> booksList1, List<String> quantityList1, String page) {

        initComponents();
        
        prevPage = page;
        
        Color x = new Color(32, 55, 73);
        this.getContentPane().setBackground(x);
        
        Color y = new Color(205, 0, 69);
        addButton.setBackground(y);
        
        Color z = new Color(102, 102, 102);
        cancelButton.setBackground(z);
        
        purchaseOrderNumber = purchaseOrderNumber1;
        contactPerson = contactPerson1;
        outlet = outlet1;
        dateToday = dateToday1;
        booksList = booksList1;
        quantityList = quantityList1;
        System.out.println(booksList +"booksList");
        System.out.println(quantityList + "quantityList");       
        if(booksList != null && quantityList !=null)
        {
        	System.out.println("pasok dito");  
        	displayTable2(booksList, quantityList);
        }
        getItemCodeList();
        co = new String[bookAutoList.size()];
        bookAutoList.toArray(co);
        AutoCompleteSupport.install(comboBox, GlazedLists.eventListOf(co));
 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        addButton = new javax.swing.JButton();
        cancelButton = new javax.swing.JButton();
        addBookToPOLabel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        booksTable = new javax.swing.JTable();
       
        booksTable.addKeyListener(new KeyAdapter() {
    		@Override
    		public void keyPressed(KeyEvent e) {
    			if(e.getKeyCode() == KeyEvent.VK_ENTER )
    			{
    		        System.out.println("Enter pressed");
    		        addRow();
    			}
    		}
    	});
        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Add Book to Purchase Order");
        setResizable(false);

        addButton.setBackground(new java.awt.Color(205, 0, 69));
        addButton.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        addButton.setForeground(new java.awt.Color(255, 255, 255));
        addButton.setText("Add Book to PO");
        addButton.setBorder(null);
        addButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        addButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addButtonActionPerformed(evt);
            }
        });

        cancelButton.setBackground(new java.awt.Color(102, 102, 102));
        cancelButton.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        cancelButton.setForeground(new java.awt.Color(255, 255, 255));
        cancelButton.setText("Cancel");
        cancelButton.setBorder(null);
        cancelButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });

        addBookToPOLabel.setFont(new java.awt.Font("Calibri", 0, 16)); // NOI18N
        addBookToPOLabel.setForeground(new java.awt.Color(255, 255, 255));
        addBookToPOLabel.setText("ADD BOOK TO PURCHASE ORDER");

        booksTable.setFont(new java.awt.Font("Calibri", 0, 13)); // NOI18N
        booksTable.setForeground(new java.awt.Color(51, 51, 51));
        booksTable.setModel(new DefaultTableModel(
        	new Object[][] {
        		{null, null, null, null},
        		{null, null, null, null},
        		{null, null, null, null},
        		{null, null, null, null},
        		{null, null, null, null},
        		{null, null, null, null},
        		{null, null, null, null},
        		{null, null, null, null},
        		{null, null, null, null},
        		{null, null, null, null},
        		{null, null, null, null},
        		{null, null, null, null},
        		{null, null, null, null},
        		{null, null, null, null},
        		{null, null, null, null},
        		{null, null, null, null},
        		{null, null, null, null},
        		{null, null, null, null},
        	},
        	new String[] {
        		"ITEM CODE", "TITLE", "STOCKS ON HAND", "ORDER"
        	}
        ));
        

        booksTable.setToolTipText("");
        booksTable.setCellSelectionEnabled(true);
        booksTable.setGridColor(new java.awt.Color(204, 204, 255));
        booksTable.setRequestFocusEnabled(false);
        booksTable.setRowHeight(18);
        booksTable.getTableHeader().setReorderingAllowed(false);
        
       
        TableColumn itemCodeColumn = booksTable.getColumnModel().getColumn(0);

        itemCodeColumn.setCellEditor(new DefaultCellEditor(comboBox));
        
        comboBox.addActionListener(new ActionListener() {
			
			@Override
			public void actionPerformed(ActionEvent arg0) {
				String s = (String) comboBox.getSelectedItem();
				int row = booksTable.getSelectedRow();
				if(s != null)
				{
					getItemCode(s);
			       booksTable.setValueAt(title, row, 1);
			       booksTable.setValueAt(stocksOnHand, row, 2);
				}
			}
		});

        jScrollPane1.setViewportView(booksTable);
        
        JLabel lblFSee = new JLabel("F5 - See title and stocks on hand; Enter - Add more rows.");
        lblFSee.setForeground(Color.WHITE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        layout.setHorizontalGroup(
        	layout.createParallelGroup(Alignment.LEADING)
        		.addGroup(layout.createSequentialGroup()
        			.addGroup(layout.createParallelGroup(Alignment.LEADING)
        				.addGroup(layout.createSequentialGroup()
        					.addGap(36)
        					.addComponent(jScrollPane1, GroupLayout.PREFERRED_SIZE, 675, GroupLayout.PREFERRED_SIZE))
        				.addGroup(layout.createSequentialGroup()
        					.addGap(197)
        					.addComponent(addButton, GroupLayout.PREFERRED_SIZE, 167, GroupLayout.PREFERRED_SIZE)
        					.addGap(18)
        					.addComponent(cancelButton, GroupLayout.PREFERRED_SIZE, 167, GroupLayout.PREFERRED_SIZE))
        				.addGroup(layout.createSequentialGroup()
        					.addGap(261)
        					.addComponent(addBookToPOLabel))
        				.addGroup(layout.createSequentialGroup()
        					.addGap(233)
        					.addComponent(lblFSee)))
        			.addContainerGap(36, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
        	layout.createParallelGroup(Alignment.TRAILING)
        		.addGroup(layout.createSequentialGroup()
        			.addGap(40)
        			.addComponent(addBookToPOLabel)
        			.addGap(1)
        			.addComponent(lblFSee)
        			.addPreferredGap(ComponentPlacement.UNRELATED)
        			.addComponent(jScrollPane1, GroupLayout.PREFERRED_SIZE, 360, GroupLayout.PREFERRED_SIZE)
        			.addGap(18, 18, Short.MAX_VALUE)
        			.addGroup(layout.createParallelGroup(Alignment.BASELINE)
        				.addComponent(addButton, GroupLayout.PREFERRED_SIZE, 32, GroupLayout.PREFERRED_SIZE)
        				.addComponent(cancelButton, GroupLayout.PREFERRED_SIZE, 32, GroupLayout.PREFERRED_SIZE))
        			.addGap(40))
        );
        getContentPane().setLayout(layout);

        pack();
    }// </editor-fold>//GEN-END:initComponents


    private void addButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addButtonActionPerformed
    	boolean go = true;
    	try{
        	booksList = new ArrayList<String>();
        	quantityList = new ArrayList<String>();
        	
        	int rowCount = booksTable.getRowCount();
        	for(int i=0; i<rowCount; i++) {
        	    	String selectedBook = (String) booksTable.getModel().getValueAt(i, 0);
        	    	if(selectedBook != null)
        	    	{
        	    	booksList.add(selectedBook);
        	    	}
        	    	 
        	    	if (booksTable.getModel().getValueAt(i,3) != null)
        	    	{
        	    		String quantitySelected = (String) booksTable.getModel().getValueAt(i, 3).toString();
        	    		quantityList.add(quantitySelected); 
        	    	}
   	    
        	}
	    	if(booksList.size() != 0 && quantityList.size() == 0)
	    	{
	    		go = false;
           	 JOptionPane.showMessageDialog(null, "Please enter quantity value.", "Error", JOptionPane.ERROR_MESSAGE);
	    	}      
        	
        }
        catch (Exception e){
            e.printStackTrace();
        };
        
        if(go == true)
        {
	        this.dispose();
	    	DCAddPurchaseOrderScreen a = new DCAddPurchaseOrderScreen(purchaseOrderNumber, dateToday, contactPerson, outlet, booksList, quantityList, "" );
	    	
	        if (prevPage.equals("")){
	        	a = new DCAddPurchaseOrderScreen(purchaseOrderNumber, dateToday, contactPerson, outlet, booksList, quantityList, "");
	        }
	        else if (prevPage.equals("ad")){
	        	a = new DCAddPurchaseOrderScreen(purchaseOrderNumber, dateToday, contactPerson, outlet, booksList, quantityList, "ad");
	        }
	        
	        a.setVisible(true);
        }
        
    }//GEN-LAST:event_addButtonActionPerformed

    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
     	this.dispose();
    	DCAddPurchaseOrderScreen a = new DCAddPurchaseOrderScreen(purchaseOrderNumber, dateToday, contactPerson, outlet, booksList, quantityList, "" );
    	
        if (prevPage.equals("")){
        	a = new DCAddPurchaseOrderScreen(purchaseOrderNumber, dateToday, contactPerson, outlet, booksList, quantityList, "");
        }
        else if (prevPage.equals("ad")){
        	a = new DCAddPurchaseOrderScreen(purchaseOrderNumber, dateToday, contactPerson, outlet, booksList, quantityList, "ad");
        }
        
        a.setVisible(true);
    }//GEN-LAST:event_cancelButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DCAddBookToPOScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DCAddBookToPOScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DCAddBookToPOScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DCAddBookToPOScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DCAddBookToPOScreen(purchaseOrderNumber, dateToday, contactPerson, outlet, booksList, quantityList, "").setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel addBookToPOLabel;
    private javax.swing.JButton addButton;
    private javax.swing.JTable booksTable;
    private javax.swing.JButton cancelButton;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables.
    
   
    private static void printMessage(HashMap map)
    {
        System.out.println(map.get("message"));
    }
    public static boolean checkNumber(String stringNumber)  
    {  
      try  
      {  
        double d = Double.parseDouble(stringNumber);  
      }  
      catch(NumberFormatException nfe)  
      {  
        return false;  
      }  
      return true;  
    }
    
    private void addRow()
    {
        DefaultTableModel model = (DefaultTableModel)booksTable.getModel();

       if (model != null) {
       Vector v = new Vector(1);
       for (int j = 0; j < booksTable.getColumnCount(); j++){
                v.add("");
            }
            model.addRow(v);
            }

    }
    public void getItemCodeList()
    {
    		PreparedStatement pst;
    		Connection con;
    		
    		try {

    			Class.forName("com.mysql.jdbc.Driver");
    			con = (Connection) DriverManager.getConnection("jdbc:mysql://localhost:3306/psicomims", "root", "root");
    			pst = (PreparedStatement) con.prepareStatement("SELECT * FROM book");
    			ResultSet rs = pst.executeQuery();
    		    Set<String> itemCodeSet = new HashSet();
    		    int i = 0;
    			while (rs.next()) {
    				if(!rs.getString("item_code").equals(null))
    				{
    					itemCodeSet.add(rs.getString("item_code"));
    				}
    				i++;
    			}
    			bookAutoList.addAll(itemCodeSet);
    		} catch (ClassNotFoundException e) {
    			// TODO Auto-generated catch block
    			e.printStackTrace();
    		} catch (SQLException e) {
    			// TODO Auto-generated catch block
    			e.printStackTrace();
    		}

    	
    }   
    public void getItemCode(String itemCode1)
    {
    		PreparedStatement pst;
    		Connection con;
    		
    		try {

    			Class.forName("com.mysql.jdbc.Driver");
    			con = (Connection) DriverManager.getConnection("jdbc:mysql://localhost:3306/psicomims", "root", "root");
    			pst = (PreparedStatement) con.prepareStatement("SELECT * FROM book");
    			ResultSet rs = pst.executeQuery();
    			while (rs.next()) {
    				if(rs.getString("item_code").equals(itemCode1))
    				{ 
    					title = rs.getString("title");
    					stocksOnHand = rs.getString("quantity");
    					System.out.println("got it");
    					break;
    				}
    			}
    			
    		} catch (ClassNotFoundException e) {
    			// TODO Auto-generated catch block
    			e.printStackTrace();
    		} catch (SQLException e) {
    			// TODO Auto-generated catch block
    			e.printStackTrace();
    		}		
    }
    public void displayTable2(List<String> booksList, List<String> quantityList){
    	String[] columnNames = { "ITEM CODE", "TITLE", "STOCKS ON HAND", "ORDER"};

        DefaultTableModel model = new DefaultTableModel();
        model.setColumnIdentifiers(columnNames);

        PreparedStatement pst;
        Connection con;
        
        String itemCode = "";
        String quantity = "";
        String title = "";
        String stocksOnHand = "";
        try {
        Class.forName("com.mysql.jdbc.Driver");
    	con = DriverManager.getConnection("jdbc:mysql://localhost:3306/psicomims", "root", "root");
        pst = con.prepareStatement("SELECT * FROM psicomims.book");
        ResultSet rs = pst.executeQuery();

   
            int i = 0;
            for(int j = 0; j<booksList.size(); j++)
            {
                itemCode = booksList.get(j).toString();
                while (rs.next()) {
            		if (booksList.get(j).equals(rs.getString("item_code"))) {
            			title = rs.getString("title");
            			itemCode = rs.getString("item_code");
            			stocksOnHand = rs.getString("quantity");
            			      			
            			i++;
            			break;
            		}
            	}
                quantity = quantityList.get(j).toString();
                
                model.addRow(new Object[]{itemCode, title, stocksOnHand, quantity});    
                i++;
            }
            
            if (i < 1) {
            	booksTable = new javax.swing.JTable();
            }
            
            if (i == 1) {
                System.out.println(i + " Record Found");
            } 
            
            else {
                System.out.println(i + " Records Found");
                
            }
            
                  
        } catch (Exception e) {
            e.printStackTrace();
        }
        
        booksTable = new JTable(model);
        booksTable.addKeyListener(new KeyAdapter() {
    		@Override
    		public void keyPressed(KeyEvent e) {
    			if(e.getKeyCode() == KeyEvent.VK_ENTER )
    			{
    		        System.out.println("Enter pressed");
    		        addRow();
    			}
    		}
    	});
        booksTable.setModel(model);
        booksTable.setAutoResizeMode(JTable.AUTO_RESIZE_ALL_COLUMNS);
        booksTable.setFont(new java.awt.Font("Calibri", 0, 13)); // NOI18N
        booksTable.setForeground(new java.awt.Color(51, 51, 51));
        
        booksTable.setToolTipText("");
        booksTable.setRowHeight(18);
        booksTable.setRequestFocusEnabled(false);
        booksTable.setGridColor(new Color(204, 204, 255));
        booksTable.setCellSelectionEnabled(true);
        booksTable.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setColumnHeaderView(booksTable.getTableHeader());
        jScrollPane1.setViewportView(booksTable);
    }
}
    
