package app;
import java.awt.Color;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;

import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Abby
 */
public class DCViewDeliveryReceiptScreen extends javax.swing.JFrame {

	String prevPage;
	
    /**
     * Creates new form DCViewDeliveryReceiptScreen
     */
    public DCViewDeliveryReceiptScreen(String page) {
        initComponents();
        
        prevPage = page;
        
        Color x = new Color(32, 55, 73);
        this.getContentPane().setBackground(x);
    }
    
    public DCViewDeliveryReceiptScreen(String drNumber, String dateDelivery, String totalAmount, String page) {
        initComponents();
        
        prevPage = page;
        
        Color x = new Color(32, 55, 73);
        this.getContentPane().setBackground(x);
        
        drNumberValueLabel.setText(drNumber);
        dateDeliveryValueLabel.setText(dateDelivery);
        totalAmountValueLabel.setText(totalAmount);
        
        this.displayAll(drNumber);
   }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        viewPoLabel = new javax.swing.JLabel();
        drNumberLabel = new javax.swing.JLabel();
        drNumberValueLabel = new javax.swing.JLabel();
        dateLabel = new javax.swing.JLabel();
        dateDeliveryValueLabel = new javax.swing.JLabel();
        totalAmountLabel = new javax.swing.JLabel();
        totalAmountValueLabel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        deliveryReceiptsTable = new javax.swing.JTable();
        backButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("View Delivery Receipt");
        setResizable(false);

        viewPoLabel.setFont(new java.awt.Font("Calibri", 0, 16)); // NOI18N
        viewPoLabel.setForeground(new java.awt.Color(255, 255, 255));
        viewPoLabel.setText("VIEW DELIVERY RECEIPT");

        drNumberLabel.setFont(new java.awt.Font("Calibri", 0, 15)); // NOI18N
        drNumberLabel.setForeground(new java.awt.Color(255, 255, 255));
        drNumberLabel.setText("DR Number:");

        drNumberValueLabel.setFont(new java.awt.Font("Calibri", 0, 15)); // NOI18N
        drNumberValueLabel.setForeground(new java.awt.Color(255, 255, 255));
        drNumberValueLabel.setText("<Value Here>");

        dateLabel.setFont(new java.awt.Font("Calibri", 0, 15)); // NOI18N
        dateLabel.setForeground(new java.awt.Color(255, 255, 255));
        dateLabel.setText("Date Delivery:");

        dateDeliveryValueLabel.setFont(new java.awt.Font("Calibri", 0, 15)); // NOI18N
        dateDeliveryValueLabel.setForeground(new java.awt.Color(255, 255, 255));
        dateDeliveryValueLabel.setText("<Value Here>");

        totalAmountLabel.setFont(new java.awt.Font("Calibri", 0, 15)); // NOI18N
        totalAmountLabel.setForeground(new java.awt.Color(255, 255, 255));
        totalAmountLabel.setText("Total Amount");

        totalAmountValueLabel.setFont(new java.awt.Font("Calibri", 0, 15)); // NOI18N
        totalAmountValueLabel.setForeground(new java.awt.Color(255, 255, 255));
        totalAmountValueLabel.setText("<Value Here>");

        deliveryReceiptsTable.setFont(new java.awt.Font("Calibri", 0, 13)); // NOI18N
        deliveryReceiptsTable.setForeground(new java.awt.Color(255, 255, 255));
        
        backButton.setBackground(new java.awt.Color(205, 0, 69));
        backButton.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        backButton.setForeground(new java.awt.Color(255, 255, 255));
        backButton.setText("Back");
        backButton.setBorder(null);
        backButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(backButton, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(47, 47, 47))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 710, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(300, 300, 300)
                        .addComponent(viewPoLabel))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(dateLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(dateDeliveryValueLabel))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(totalAmountLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(totalAmountValueLabel))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(drNumberLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(drNumberValueLabel)))))
                .addContainerGap(25, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(viewPoLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 21, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(drNumberLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(drNumberValueLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dateLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dateDeliveryValueLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(totalAmountLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(totalAmountValueLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 402, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(backButton, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
    	this.dispose();
        DCIncompleteDeliveryReceiptsTab a = new DCIncompleteDeliveryReceiptsTab("");
        
        if (prevPage.equals("")){
        	a = new DCIncompleteDeliveryReceiptsTab("");
       	}
    	else if (prevPage.equals("ad")){
    		a = new DCIncompleteDeliveryReceiptsTab("ad");
     	}
        
        a.setVisible(true);  
    }//GEN-LAST:event_backButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DCViewDeliveryReceiptScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DCViewDeliveryReceiptScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DCViewDeliveryReceiptScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DCViewDeliveryReceiptScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DCViewDeliveryReceiptScreen("").setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backButton;
    private javax.swing.JLabel dateDeliveryValueLabel;
    private javax.swing.JLabel dateLabel;
    private javax.swing.JTable deliveryReceiptsTable;
    private javax.swing.JLabel drNumberLabel;
    private javax.swing.JLabel drNumberValueLabel;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel totalAmountLabel;
    private javax.swing.JLabel totalAmountValueLabel;
    private javax.swing.JLabel viewPoLabel;
    // End of variables declaration//GEN-END:variables
    
    public void displayAll(String drNumber){
    	String[] columnNames = {"ITEM CODE", "TITLE", "QUANTITY"};

        DefaultTableModel model = new DefaultTableModel();
        model.setColumnIdentifiers(columnNames);
        
        PreparedStatement pst;
        Connection con;
        
        String itemCode = "";
        String title = "";
        String quantity = "";

        try {
        	Class.forName("com.mysql.jdbc.Driver");
        	con = DriverManager.getConnection("jdbc:mysql://localhost:3306/psicomims", "root", "root");
           	pst = con.prepareStatement("SELECT d.book_id, d.quantity, b.title FROM psicomims.book b, psicomims.specific_dr d WHERE b.item_code=d.book_id AND d.dr_id=" + drNumber);  	
        	ResultSet rs = pst.executeQuery();
            int i = 0;
            while (rs.next()) {
                title = rs.getString("title");
                itemCode = rs.getString("book_id");
                quantity = rs.getString("quantity");
                model.addRow(new Object[]{itemCode, title, quantity});
                i++;
            }
            
            if (i < 1){
            
                JOptionPane.showMessageDialog(null, "No Record Found", "Error", JOptionPane.ERROR_MESSAGE);
            }
            
            if (i == 1) {
                System.out.println(i + " Record Found");
            } 
            
            else {
                System.out.println(i + " Records Found");
            }

                  
        } catch (Exception e) {
            e.printStackTrace();
        }
        
        deliveryReceiptsTable = new JTable(model);
        deliveryReceiptsTable.setModel(model);
        deliveryReceiptsTable.setAutoResizeMode(JTable.AUTO_RESIZE_ALL_COLUMNS);
        deliveryReceiptsTable.setToolTipText("");
        deliveryReceiptsTable.setCellSelectionEnabled(true);
        deliveryReceiptsTable.setGridColor(new java.awt.Color(204, 204, 255));
        deliveryReceiptsTable.setRequestFocusEnabled(false);
        deliveryReceiptsTable.setRowHeight(18);
        deliveryReceiptsTable.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(deliveryReceiptsTable);
        deliveryReceiptsTable.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_INTERVAL_SELECTION);
    
        }
}
