package app;

import java.awt.Color;
import java.awt.Font;
import java.awt.event.FocusEvent;
import java.awt.event.FocusListener;
import java.awt.font.TextAttribute;
import java.util.Map;
import java.awt.Frame;
import javax.swing.GroupLayout.Alignment;
import javax.swing.GroupLayout;
import javax.swing.LayoutStyle.ComponentPlacement;
import javax.swing.JButton;
import javax.swing.border.BevelBorder;
import java.awt.SystemColor;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Abby
 */
public class WCHomeScreen extends javax.swing.JFrame {

    /**
     * Creates new form WCHomeScreen
     */
    public WCHomeScreen() {
    	setExtendedState(Frame.MAXIMIZED_BOTH);
        initComponents();
        
        Color x = new Color(32, 55, 73);
        this.getContentPane().setBackground(x);
        
        signOutButton.addMouseListener(new java.awt.event.MouseAdapter() {
            Font originalFont = null;
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                originalFont = signOutButton.getFont();
                Map attributes = originalFont.getAttributes();
                attributes.put(TextAttribute.UNDERLINE, TextAttribute.UNDERLINE_ON);
                signOutButton.setFont(originalFont.deriveFont(attributes));
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                signOutButton.setFont(originalFont);
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        logoLabel = new javax.swing.JLabel();
        mainPanel = new javax.swing.JPanel();
        copyrightLabel1 = new javax.swing.JLabel();
        updateButton = new javax.swing.JButton();
        defButton = new javax.swing.JButton();
        dispButton = new javax.swing.JButton();
        greetingLabel = new javax.swing.JLabel();
        signOutButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Home");

        logoLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/VS2.1.png"))); // NOI18N

        mainPanel.setBackground(new java.awt.Color(227, 234, 245));
        mainPanel.setAlignmentX(0.0F);
        mainPanel.setAlignmentY(0.0F);

        copyrightLabel1.setFont(new java.awt.Font("Calibri", 0, 8)); // NOI18N
        copyrightLabel1.setForeground(new java.awt.Color(32, 55, 73));
        copyrightLabel1.setText("© 2016 PSICOM Inventory Mgt. System Powered by VIPE Solutions. All Rights Reserved. ");

        updateButton.setBackground(new java.awt.Color(255, 255, 255));
        updateButton.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        updateButton.setForeground(new java.awt.Color(255, 255, 255));
        updateButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/home_up.png"))); // NOI18N
        updateButton.setToolTipText("Update Stocks");
        updateButton.setAlignmentY(0.0F);
        updateButton.setBorder(null);
        updateButton.setBorderPainted(false);
        updateButton.setContentAreaFilled(false);
        updateButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        updateButton.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/images/home_up2.png"))); // NOI18N
        updateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateButtonActionPerformed(evt);
            }
        });

        defButton.setBackground(new java.awt.Color(255, 255, 255));
        defButton.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        defButton.setForeground(new java.awt.Color(255, 255, 255));
        defButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/home_def.png"))); // NOI18N
        defButton.setToolTipText("Defective Books");
        defButton.setAlignmentY(0.0F);
        defButton.setBorder(null);
        defButton.setBorderPainted(false);
        defButton.setContentAreaFilled(false);
        defButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        defButton.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/images/home_def2.png"))); // NOI18N
        defButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                defButtonActionPerformed(evt);
            }
        });

        dispButton.setBackground(new java.awt.Color(255, 255, 255));
        dispButton.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        dispButton.setForeground(new java.awt.Color(255, 255, 255));
        dispButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/home_disp.png"))); // NOI18N
        dispButton.setToolTipText("Display Orders");
        dispButton.setAlignmentY(0.0F);
        dispButton.setBorder(null);
        dispButton.setBorderPainted(false);
        dispButton.setContentAreaFilled(false);
        dispButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        dispButton.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/images/home_disp2.png"))); // NOI18N
        dispButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dispButtonActionPerformed(evt);
            }
        });
        
        outboundButton = new JButton();
        outboundButton.setText("OUTBOUND");
        outboundButton.setToolTipText("");
        outboundButton.setForeground(Color.BLACK);
        outboundButton.setFont(new Font("Calibri", Font.PLAIN, 12));
        outboundButton.setContentAreaFilled(false);
        outboundButton.setBorder(new BevelBorder(BevelBorder.LOWERED, null, null, null, null));
        outboundButton.setBackground(SystemColor.windowBorder);
        outboundButton.setAlignmentY(0.0f);

        javax.swing.GroupLayout mainPanelLayout = new javax.swing.GroupLayout(mainPanel);
        mainPanelLayout.setHorizontalGroup(
        	mainPanelLayout.createParallelGroup(Alignment.TRAILING)
        		.addGroup(mainPanelLayout.createSequentialGroup()
        			.addGroup(mainPanelLayout.createParallelGroup(Alignment.LEADING)
        				.addGroup(mainPanelLayout.createSequentialGroup()
        					.addGap(18)
        					.addComponent(copyrightLabel1))
        				.addGroup(mainPanelLayout.createSequentialGroup()
        					.addGap(341)
        					.addComponent(dispButton)
        					.addGap(64)
        					.addComponent(defButton)
        					.addGap(58)
        					.addComponent(updateButton)
        					.addGap(62)
        					.addComponent(outboundButton, GroupLayout.PREFERRED_SIZE, 125, GroupLayout.PREFERRED_SIZE)))
        			.addContainerGap(298, Short.MAX_VALUE))
        );
        mainPanelLayout.setVerticalGroup(
        	mainPanelLayout.createParallelGroup(Alignment.LEADING)
        		.addGroup(Alignment.TRAILING, mainPanelLayout.createSequentialGroup()
        			.addGap(192)
        			.addGroup(mainPanelLayout.createParallelGroup(Alignment.LEADING)
        				.addComponent(dispButton)
        				.addGroup(mainPanelLayout.createParallelGroup(Alignment.LEADING)
        					.addComponent(outboundButton, GroupLayout.PREFERRED_SIZE, 113, GroupLayout.PREFERRED_SIZE)
        					.addGroup(mainPanelLayout.createParallelGroup(Alignment.LEADING)
        						.addComponent(updateButton)
        						.addComponent(defButton))))
        			.addPreferredGap(ComponentPlacement.RELATED, 275, Short.MAX_VALUE)
        			.addComponent(copyrightLabel1, GroupLayout.PREFERRED_SIZE, 14, GroupLayout.PREFERRED_SIZE)
        			.addGap(7))
        );
        mainPanel.setLayout(mainPanelLayout);

        greetingLabel.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        greetingLabel.setForeground(new java.awt.Color(255, 255, 255));
        greetingLabel.setText("Hello, Warehouse Clerk  | ");

        signOutButton.setFont(new java.awt.Font("Calibri", 0, 11)); // NOI18N
        signOutButton.setForeground(new java.awt.Color(255, 255, 255));
        signOutButton.setText("Sign Out");
        signOutButton.setBorder(null);
        signOutButton.setBorderPainted(false);
        signOutButton.setContentAreaFilled(false);
        signOutButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        signOutButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                signOutButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        layout.setHorizontalGroup(
        	layout.createParallelGroup(Alignment.LEADING)
        		.addGroup(layout.createSequentialGroup()
        			.addComponent(logoLabel)
        			.addPreferredGap(ComponentPlacement.RELATED, 892, Short.MAX_VALUE)
        			.addComponent(greetingLabel)
        			.addPreferredGap(ComponentPlacement.RELATED)
        			.addComponent(signOutButton)
        			.addGap(20))
        		.addGroup(layout.createSequentialGroup()
        			.addGap(10)
        			.addComponent(mainPanel, GroupLayout.DEFAULT_SIZE, 1352, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
        	layout.createParallelGroup(Alignment.LEADING)
        		.addGroup(layout.createSequentialGroup()
        			.addGroup(layout.createParallelGroup(Alignment.LEADING)
        				.addGroup(layout.createSequentialGroup()
        					.addContainerGap()
        					.addComponent(logoLabel))
        				.addGroup(layout.createSequentialGroup()
        					.addGap(25)
        					.addGroup(layout.createParallelGroup(Alignment.BASELINE)
        						.addComponent(signOutButton)
        						.addComponent(greetingLabel))))
        			.addGap(18)
        			.addComponent(mainPanel, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        getContentPane().setLayout(layout);

    }// </editor-fold>//GEN-END:initComponents

    private void updateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateButtonActionPerformed
    	this.dispose();
        WCUpdateStocksTab a = new WCUpdateStocksTab();
        a.setVisible(true);
    }//GEN-LAST:event_updateButtonActionPerformed

    private void defButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_defButtonActionPerformed
    	this.dispose();
        WCDefectiveBookRecordTab a = new WCDefectiveBookRecordTab();
        a.setVisible(true);
    }//GEN-LAST:event_defButtonActionPerformed

    private void dispButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dispButtonActionPerformed
    	this.dispose();
        WCDisplayIncompleteOrdersTab a = new WCDisplayIncompleteOrdersTab();
        a.setVisible(true);
    }//GEN-LAST:event_dispButtonActionPerformed

    private void signOutButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_signOutButtonActionPerformed
    	this.dispose();
        WCLogInScreen a = new WCLogInScreen();
        a.setVisible(true);
    }//GEN-LAST:event_signOutButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(WCHomeScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(WCHomeScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(WCHomeScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(WCHomeScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new WCHomeScreen().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel copyrightLabel1;
    private javax.swing.JButton defButton;
    private javax.swing.JButton dispButton;
    private javax.swing.JLabel greetingLabel;
    private javax.swing.JLabel logoLabel;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JButton signOutButton;
    private javax.swing.JButton updateButton;
    private JButton outboundButton;
    // End of variables declaration//GEN-END:variables
}
